Meeting attendance record page
sws2apps/organized-app pull request #1888
Opened 2024-06-03 20:47 UTC by Logan08691

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-03 20:47 UTC, rhahao commented
Task linked: [CU-86bwch8f4 Meeting attendance record page](https://app.clickup.com/t/86bwch8f4)

2024-06-04 09:59 UTC, rhahao requested changes

2024-06-04 09:59 UTC, rhahao commented on src/current/App.jsx
> +        if (import.meta.env.API_HOST_PORT) {
@Logan08691: I think this proposed can be reverted. 😊 The CPE app should no longer need such customization, I guess...

2024-06-04 09:59 UTC, rhahao commented on src/v3/components/card_header/index.styles.ts
> +export const StyledContentBox = styled(Box)<{ color: string; size: CardHeaderSizeType }>((props) => ({
@Logan08691: please fix this code in order for these props to not end up in the DOM. Probably, they will cause too much noises in the dev console.

2024-06-04 09:59 UTC, rhahao commented on src/v3/components/card_header/index.tsx
> +      {children && <Collapse in={isExpanded}>{children}</Collapse>}
@Logan08691: please adjust this comparison as reported to use strict equality for consistency.

2024-06-04 09:59 UTC, rhahao commented on src/v3/hooks/useGlobal.tsx
> +          if (import.meta.env.API_HOST_PORT) {
@Logan08691: I think the `VITE_BACKEND_API` env should already be enough for overriding this api check. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_results/index.styles.tsx
> +export const StyledColumnBox = styled(Box)(({ gap }: { gap: string }) => ({
@Logan08691: please make sure this `gap` prop does not create the invalid prop on a DOM element error.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_results/index.tsx
> +  t,
@Logan08691: for consistency, just use the `t` function from the `useAppTranslation` hook on this file. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_results/index.tsx
> +        ></Box>
@Logan08691: you may want to apply this suggestion as well. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_toolbar/index.styles.tsx
> +export const StyledBox = styled(Box)(({ laptopView }: { laptopView: boolean }) => ({
@Logan08691: please fix this code as well since the `laptoView` prop will produce error in the dev console. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_toolbar/index.tsx
> +};
@Logan08691: thank you for applying this suggestion as well.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/report_toolbar/index.types.tsx
> +  t: TFunction<'translation', undefined>;
@Logan08691: this should not be needed since the `t` function from our hook can already be used in code. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/total_box/index.styles.tsx
> +export const StyledBox = styled(Box)(({ laptopView }: { laptopView: boolean }) => ({
@Logan08691: please adjust this to prevent the Invalid prop to DOM error. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/total_box/index.styles.tsx
> +export const StyledColorBox = styled(Box)<{ backgroudColor: string }>((props) => ({
@Logan08691: please adjust this to prevent the Invalid prop to DOM error. Thank you.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/total_box/index.styles.tsx
> +}));
@Logan08691: you may want to apply this suggestion too. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/week_box/index.styles.tsx
> +export const StyledTodayTypography = styled(Typography)(({ color }: { color: string }) => ({
@Logan08691: please make sure that this not produce the Invalid prop to DOM error. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/week_box/index.tsx
> +  const isWeekend = dayStr == 'Sat' || dayStr == 'Sun';
@Logan08691: please apply the suggestion for consistency. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/components/week_box/index.types.tsx
> +  t: TFunction<'translation', undefined>;
@Logan08691: we should not need this. Directly use the `t` function from the hook. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/index.styles.tsx
> +export const StyledBox = styled(Box)(({ row }: { row: boolean }) => ({
@Logan08691: please fix this code to prevent the Invalid prop to a DOM error. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/index.styles.tsx
> +export const StyledReportBox = styled(Box)(({ desktopView }: { desktopView: boolean }) => ({
@Logan08691: please fix this code to prevent the Invalid prop to a DOM error. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/index.styles.tsx
> +export const StyledColumnBox = styled(Box)(({ gap }: { gap: string }) => ({
@Logan08691: please make sure that this does not produce the Invalid prop to a DOM error. Thanks.

2024-06-04 09:59 UTC, rhahao commented on src/v3/pages/reports/meeting_attendance/index.tsx
> +    if (value != 0) {
@Logan08691: please apply the suggestion as requested too. Thanks.

2024-06-26 22:10 UTC, Logan08691 commented on src/v3/pages/reports/meeting_attendance/components/report_toolbar/index.tsx
> +};
@rhahao I skipped dependencies for run this useEffect only once. Let me know please if we have some utilities for do that in the right way.

2024-07-02 04:49 UTC, rhahao approved these changes

2024-07-02 04:50 UTC, merged