fix(reports): S-21 export checkboxes – make indeterminate
sws2apps/organized-app pull request #3164
Opened 2024-12-06 20:55 UTC by FussuChalice

# Description

remove parent check if at least one child element has been unchecked.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-12-06 20:55 UTC, rhahao commented
Task linked: [CU-86c0wky89 [FIX] S-21 export checkboxes – make indeterminate](https://app.clickup.com/t/86c0wky89)

2024-12-07 04:39 UTC, rhahao requested changes

2024-12-07 04:39 UTC, rhahao commented on src/features/reports/publisher_records/export_S21/specific_records/useParentUncheckHandler.tsx
> +    dataSource,
@FussuChalice: it seems like the type is not set for this one. Could you please add it? Thanks.

2024-12-08 10:16 UTC, sws2apps-admin approved these changes

2024-12-08 10:16 UTC, rhahao approved these changes

2024-12-08 10:17 UTC, merged

2024-12-08 12:49 UTC, rhahao commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on [GitHub release](https://github.com/sws2apps/organized-app/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: