feat(meetings): add month sorting | fix #3239
sws2apps/organized-app pull request #3282
Opened 2024-12-23 14:39 UTC by FussuChalice

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-12-23 14:39 UTC, rhahao commented
Task linked: [CU-86c1br7q3 [FEAT] Add month sorting](https://app.clickup.com/t/86c1br7q3)

2024-12-23 18:10 UTC, ux-git commented
I'm sorry @FussuChalice but I mixed up the icons in Figma. Could you re-import the updated ones?

2024-12-25 08:14 UTC, rhahao requested changes

2024-12-25 08:14 UTC, rhahao commented on src/features/meetings/week_selector/useWeekSelector.tsx
@FussuChalice: could you please add the functionality to store the sorting preference in localStorage and initially load that value when opening this form? Thank you.

2024-12-25 19:43 UTC, FussuChalice commented on src/features/meetings/week_selector/useWeekSelector.tsx
Okay. No problem.

2024-12-28 07:50 UTC, ux-git commented
@FussuChalice could you please also slightly align the sorting icon to stay in the middle instead of the top **on mobile**? <img width="128" alt="Screenshot 2024-12-28 at 08 49 08" src="https://github.com/user-attachments/assets/47c6fbcb-eddd-4fd5-add8-69fcbdca2a85" />

<img width="136" alt="Screenshot 2024-12-28 at 08 50 11" src="https://github.com/user-attachments/assets/d3ce6ba2-8df7-471a-942e-a5bc07b4640d" />

2025-01-05 05:57 UTC, rhahao approved these changes

2025-01-05 05:58 UTC, merged

2025-01-15 01:18 UTC, rhahao commented
:tada: This PR is included in version 3.6.0 :tada:

The release is available on [GitHub release](https://github.com/sws2apps/organized-app/releases/tag/v3.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: